[package]
name = "sniff"
version = "0.1.0"
edition = "2021"

[dependencies]
anstyle = "1.0.7"
clap = { version = "4.5.4", features = ["derive"] }
nom = "7.1.3"
pnet = "0.34.0"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
